name: Compile Examples

# See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage caused by changes to external resources (libraries, platforms).
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: arduino:samd:arduino_zero_edbg
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:mkr1000
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:mkrzero
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:mkrwifi1010
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:mkrfox1200
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:mkrwan1300
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:mkrwan1310
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:mkrgsm1400
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:mkrnb1500
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:mkrvidor4000
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:nano_33_iot
            platforms: |
              - name: arduino:samd
          - fqbn: arduino:samd:tian
            platforms: |
              - name: arduino:samd
            sketch-paths: |
              - examples/Example1-Set_Time
              - examples/Example10_GNSS_Sync_with_Time_Zone_Support
              - examples/Example2-Print_Time
              - examples/Example3A-Set_Hundredths_Software
              - examples/Example3B-Set_Hundredths_Hardware
              - examples/Example4A-Alarm_Interrupt
              - examples/Example4B-Countdown_Interrupt
              - examples/Example4C-Periodic_Interrupt
              - examples/Example5-Timestamp
              - examples/Example6-Fine_Tuning
              - examples/Example7-Print_Epoch
              - examples/Example8-Set_Epoch
              - examples/Example9_Time_Zone_Support
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GH_REPO_TOKEN }}
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          libraries: |
            # Install the library from the local path.
            - source-path: ./
            - name: FC0003390327
          sketch-paths: |
            # Sketches to compile for all boards
            - examples/Example1-Set_Time
            - examples/Example10_GNSS_Sync_with_Time_Zone_Support
            - examples/Example2-Print_Time
            - examples/Example3A-Set_Hundredths_Software
            - examples/Example3B-Set_Hundredths_Hardware
            - examples/Example4A-Alarm_Interrupt
            - examples/Example4B-Countdown_Interrupt
            - examples/Example4C-Periodic_Interrupt
            - examples/Example5-Timestamp
            - examples/Example6-Fine_Tuning
            - examples/Example7-Print_Epoch
            - examples/Example8-Set_Epoch
            - examples/Example9_Time_Zone_Support
            # Board-specific sketches
            ${{ matrix.board.sketch-paths }}
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save sketches report as workflow artifact
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: ${{ env.SKETCHES_REPORTS_PATH }}
